name: matchmaker

services:
  db:
    container_name: matchmaker_database
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: MatchMaker!
    volumes:
      - sql-data:/var/opt/mssql/data
    ports:
      - "1433:1433"
    user: root
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "MatchMaker!" -Q "SELECT 1" -C || exit 1
      interval: 1s
      timeout: 1s
      retries: 300

  webapi:
    container_name: matchmaker_api
    build:
      context: backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  sql-data:
    name: matchmaker_db_data
